version: "3"
services:
  test:
    build: ./web/
    restart: always
    ports:
    - "18080:8080"
    environment:
      username: lzz
      password: lzz
      url: jdbc:mysql://mysql:3306/sakila?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
    - mysql

  mysql:
    network_mode: "bridge"
    container_name: v1-mysql
    image: registry.saas.hand-china.com/tools/mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      MYSQL_USER: lzz
      MYSQL_PASSWORD: lzz
    ports:
    - "3306:3306"
    volumes:
    - ./db:/docker-entrypoint-initdb.d

